[package]
name = "marshal-rson"
version = "0.1.0"
edition = "2021"

[dependencies]
marshal = {workspace = true}
anyhow = {workspace = true}
base64 = {workspace = true}

[dev-dependencies]
marshal = {workspace = true,features = ["ordered-float"]}
ordered-float = {workspace = true}
