[package]
name = "marshal-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
weak-table = {workspace=true}
marshal = {workspace=true}
anyhow = {workspace=true}
marshal-pointer = {workspace=true}
pretty_assertions = {workspace=true}

[dev-dependencies]
marshal-json={workspace=true}